/*
Highly divisible triangular number
Problem 12 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
https://projecteuler.net/problem=12

TODO : too slow, optimize later
 */

#include <stdio.h>
#include <stdlib.h>

unsigned long long sumto(unsigned int num){
    unsigned long long sum = 0;

    sum = (num * (num + 1))/2;
    return sum;
}

unsigned int ndivisor(unsigned long long num){
    unsigned int n = 0;

    for(unsigned long long i = num; i>0;i--){
        if(num % i == 0)
            n++;
    }

    return n;
}

int main(int argc, char** argv) {

    unsigned long num = 1;
    unsigned long long cursumto = 0;

    while(1){
        cursumto = sumto(num);
        unsigned long ndiv = ndivisor(cursumto);
        /*if(num % 100 == 0){
            printf("current triangle number is %lu\n", cursumto);
            printf("current number is %lu\n", num);
            printf("ndivisor is %lu\n", ndiv);
        }
        */

        if(ndiv > 500){
            break;
        }
        num++;
    }

    printf("First triangle number with more than 500 divisors is : %lu\n",cursumto);

    return (EXIT_SUCCESS);
}