/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

 #include <stdio.h>
 #include <stdlib.h>

int main(int argc, char** argv) {
    
    int i1,i2,i3;
    int sum;
    
    i1=0;
    i2=1;
    i3=1;
    
    sum=0;
    
    while(i3<4000000){
        i3=i1+i2;
        i1=i2;
        i2=i3;        
        if(i3%2==0) sum+=i3;
    }
    
    printf("Sum is : %i\n",sum);
    
    return (0);
}

